[package]
name = "plex"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-core = "0.4.0"
log = "0.4.29"
thiserror-no-std = "2.0.2"
uefi = { version = "0.36.1", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
